### ISSUE TITLE
Unable to publish to remote repository 

### ISSUE THREAD

**Issue by misschinatown** [Montana-Media-Arts/341-work#11] opened 2017-02-06 02:40 UTC
HI there! 
I need some help! I am trying to publish my local repository to a remote (GitHub) and it won't go! In SourceTree it is just saying to please wait. But nothing happens! I also tried the GitHub Desktop App and it also will not publish to remote repository. 

Any suggestions? Thank you!

**Comment by egriffin2** [comment] 2017-02-06 05:10
Did you make sure you unchecked the "This is a private repository" box?  I was having the exact same problem, if I understand right.  Mine was just telling me to wait and when I clicked on it I got a message that said I couldn't publish a private repository.  I had just forgotten to uncheck the box and as soon as I did it worked fine. Could that be it?

**Comment by michaelmusick** [comment] 2017-02-07 18:32
Thank you @egriffin2 for the suggestion. Did that work @misschinatown?

Also, this issue is a duplicate of Issue #8 

Please continue your discussion there.

**Closed as completed by michaelmusick** 2017-02-07 18:32 UTC
